"""
Inspection mask system.

Phase 1: Manual polygon mask — user draws exclusion regions.
Phase 2: Auto-detect specular reflections → suggest mask.
Phase 3: Feature-based mask alignment — ORB keypoint matching + RANSAC.
         Finds ANY feature (corners, holes, edges, textures) by pixel
         descriptor matching. No hardcoded shapes. Works on any part.

Alignment pipeline:
  1. ORB keypoint detection in both images (2000 features, adaptive)
  2. BFMatcher + Lowe ratio test → filter good matches
  3. RANSAC + estimateAffinePartial2D → rigid transform (Δx, Δy, θ, scale)
  4. Confidence = inlier_ratio × min(1, n_inliers/20)
  5. Transform mask polygon vertices with the 2×3 matrix

Convention: polygons = EXCLUDED regions (dark overlay = ignored in metrics).
"""

import json
import numpy as np
import cv2
from dataclasses import dataclass
from typing import Optional


# ── Mask data ──────────────────────────────────────────────────────────────

@dataclass
class MaskData:
    """
    One or more polygons defining the VALID inspection region.
    Pixels inside polygons → analyzed by focus + quality engines.
    Pixels outside → excluded from all metrics.
    """
    polygons:         list         # list of polygons; each = list of [x, y] int pairs
    image_shape:      tuple        # (H, W) of the source image
    source_image:     str  = ""    # filename this was drawn/detected on
    auto_detected:    bool = False  # True if generated by detect_reflections()
    align_confidence: float = 100.0 # 0–100; set by align_mask()
    n_match_inliers:  int  = 0     # ORB inliers used for last alignment

    # ── Rasterization ───────────────────────────────────────────────────

    def to_array(self, target_shape: tuple = None) -> np.ndarray:
        """
        Rasterize all polygons into a binary mask.
        Polygons = EXCLUDED regions. Returns uint8 array:
          1 = valid pixel  (analyze this)
          0 = excluded pixel (inside a drawn polygon — ignored)
        No polygons → all-ones (full image analyzed).
        """
        H, W = target_shape if target_shape else self.image_shape
        if not self.polygons:
            return np.ones((H, W), dtype=np.uint8)
        mask = np.ones((H, W), dtype=np.uint8)   # start: everything valid
        for poly in self.polygons:
            pts = np.array(poly, dtype=np.int32).reshape(-1, 1, 2)
            cv2.fillPoly(mask, [pts], 0)          # drawn polygon = excluded
        return mask

    def coverage_pct(self, target_shape: tuple = None) -> float:
        """Percentage of image area that is EXCLUDED (inside drawn polygons)."""
        arr = self.to_array(target_shape)
        excluded = arr.size - int(arr.sum())
        return float(excluded) / arr.size * 100.0

    # ── Geometric transform ──────────────────────────────────────────────

    def transform(self, warp_matrix: np.ndarray,
                  target_shape: tuple) -> "MaskData":
        """
        Apply a 2×3 affine (Euclidean) warp to all polygon vertices.
        Returns a new MaskData in target_shape coordinates.
        """
        H, W = target_shape
        new_polys = []
        for poly in self.polygons:
            if not poly:
                continue
            pts = np.array(poly, dtype=np.float32).reshape(-1, 1, 2)
            t   = cv2.transform(pts, warp_matrix).reshape(-1, 2)
            t[:, 0] = np.clip(t[:, 0], 0, W - 1)
            t[:, 1] = np.clip(t[:, 1], 0, H - 1)
            new_polys.append(t.astype(int).tolist())
        return MaskData(
            polygons         = new_polys,
            image_shape      = target_shape,
            source_image     = self.source_image,
            auto_detected    = self.auto_detected,
            align_confidence = self.align_confidence,
        )

    # ── Persistence ──────────────────────────────────────────────────────

    def save(self, path: str):
        with open(path, "w", encoding="utf-8") as f:
            json.dump({
                "polygons":         self.polygons,
                "image_shape":      list(self.image_shape),
                "source_image":     self.source_image,
                "auto_detected":    self.auto_detected,
                "align_confidence": self.align_confidence,
                "n_match_inliers":  self.n_match_inliers,
            }, f, indent=2)

    @classmethod
    def load(cls, path: str) -> "MaskData":
        with open(path, encoding="utf-8") as f:
            d = json.load(f)
        return cls(
            polygons         = d["polygons"],
            image_shape      = tuple(d["image_shape"]),
            source_image     = d.get("source_image",     ""),
            auto_detected    = d.get("auto_detected",    False),
            align_confidence = d.get("align_confidence", 100.0),
            n_match_inliers  = d.get("n_match_inliers",  0),
        )


# ── Mask engine ────────────────────────────────────────────────────────────

class MaskEngine:

    # ── Phase 2: Auto-detect specular reflections ─────────────────────────

    @staticmethod
    def detect_reflections(
        image:          np.ndarray,
        bright_thresh:  int   = 228,
        sat_thresh:     int   = 55,
        min_area_pct:   float = 0.3,
    ) -> Optional[MaskData]:
        """
        Detect specular reflection regions and return a MaskData that defines
        the VALID inspection region (everything except the reflections).

        Specular reflections in industrial images are:
          - Very bright  (HSV V channel > bright_thresh)
          - Nearly white (HSV S channel < sat_thresh — colorless)

        Both conditions together isolate specular highlights far better than
        brightness alone (which would also flag light-colored parts).

        Returns None if no significant reflections are found.
        """
        img8 = MaskEngine._to_8bit(image)
        if img8.ndim == 2:
            bgr = cv2.cvtColor(img8, cv2.COLOR_GRAY2BGR)
        else:
            bgr = cv2.cvtColor(img8, cv2.COLOR_RGB2BGR)

        H, W = bgr.shape[:2]
        hsv  = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
        V    = hsv[:, :, 2]
        S    = hsv[:, :, 1]

        # Specular mask: bright AND desaturated
        spec = ((V > bright_thresh) & (S < sat_thresh)).astype(np.uint8) * 255

        # Morphological operations:
        #   Close (21×21)  — fill holes inside reflection blobs
        #   Open  (5×5)    — remove isolated noise pixels
        k21 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (21, 21))
        k5  = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,   5))
        spec = cv2.morphologyEx(spec, cv2.MORPH_CLOSE, k21)
        spec = cv2.morphologyEx(spec, cv2.MORPH_OPEN,  k5)

        contours, _ = cv2.findContours(spec, cv2.RETR_EXTERNAL,
                                        cv2.CHAIN_APPROX_SIMPLE)
        min_area    = H * W * (min_area_pct / 100.0)
        large       = [c for c in contours if cv2.contourArea(c) >= min_area]

        if not large:
            return None   # no significant specular reflections detected

        # Build reflection mask, invert to get valid inspection region
        ref_mask = np.zeros((H, W), dtype=np.uint8)
        cv2.drawContours(ref_mask, large, -1, 255, thickness=cv2.FILLED)

        valid = cv2.bitwise_not(ref_mask)

        # Erode slightly to keep analysis away from reflection boundaries
        k15 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (15, 15))
        valid = cv2.erode(valid, k15)

        valid_ctrs, _ = cv2.findContours(valid, cv2.RETR_EXTERNAL,
                                          cv2.CHAIN_APPROX_SIMPLE)
        if not valid_ctrs:
            return None

        # Keep only the largest contiguous valid region
        main    = max(valid_ctrs, key=cv2.contourArea)
        peri    = cv2.arcLength(main, True)
        epsilon = 0.012 * peri          # Douglas-Peucker simplification
        approx  = cv2.approxPolyDP(main, epsilon, True)
        poly    = approx.reshape(-1, 2).tolist()

        return MaskData(
            polygons      = [poly],
            image_shape   = (H, W),
            auto_detected = True,
        )

    # ── Phase 3: Feature-based mask alignment ────────────────────────────

    @staticmethod
    def align_mask(
        ref_image:  np.ndarray,
        curr_image: np.ndarray,
        ref_mask:   MaskData,
    ) -> tuple:
        """
        Transfer ref_mask from ref_image to curr_image using ORB feature matching.

        Works on ANY visual feature — holes, corners, edges, textures, part
        outlines. No shape assumptions. Pure pixel descriptor matching.

        Pipeline:
          1. ORB keypoint detection (up to 2000 features per image)
          2. BFMatcher + Lowe ratio test (0.75) → retain good matches only
          3. RANSAC + estimateAffinePartial2D → rigid transform
             (translation Δx/Δy + rotation θ + uniform scale)
          4. Confidence = inlier_ratio × clamp(n_inliers / 20, 0, 1)
          5. Apply 2×3 matrix to all polygon vertices

        Returns: (aligned_MaskData, confidence_0_to_100)
        Raises:  RuntimeError if too few features or matches found.
        """
        ref_gray  = MaskEngine._to_gray_8bit(ref_image)
        curr_gray = MaskEngine._to_gray_8bit(curr_image)
        H, W      = curr_gray.shape

        # ── Step 1: ORB detection ─────────────────────────────────────────
        orb = cv2.ORB_create(
            nfeatures    = 2000,
            scaleFactor  = 1.2,
            nlevels      = 8,
            edgeThreshold= 15,
            patchSize    = 31,
        )
        kp1, des1 = orb.detectAndCompute(ref_gray,  None)
        kp2, des2 = orb.detectAndCompute(curr_gray, None)

        if des1 is None or des2 is None or len(kp1) < 8 or len(kp2) < 8:
            raise RuntimeError(
                f"Too few keypoints: ref={len(kp1) if kp1 else 0}, "
                f"curr={len(kp2) if kp2 else 0}. "
                "Images may be too uniform or low-contrast."
            )

        # ── Step 2: Match + Lowe ratio test ──────────────────────────────
        matcher = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=False)
        raw     = matcher.knnMatch(des1, des2, k=2)
        good    = [m for m, n in raw if m.distance < 0.75 * n.distance]

        if len(good) < 8:
            raise RuntimeError(
                f"Too few good matches: {len(good)} (need ≥ 8). "
                "The two images may be from different parts or very different exposures."
            )

        src_pts = np.float32([kp1[m.queryIdx].pt for m in good]).reshape(-1, 1, 2)
        dst_pts = np.float32([kp2[m.trainIdx].pt for m in good]).reshape(-1, 1, 2)

        # ── Step 3: RANSAC rigid transform ────────────────────────────────
        warp, inliers = cv2.estimateAffinePartial2D(
            src_pts, dst_pts,
            method        = cv2.RANSAC,
            ransacReprojThreshold = 4.0,   # pixels — tight for accuracy
            maxIters      = 2000,
            confidence    = 0.995,
        )

        if warp is None:
            raise RuntimeError("RANSAC failed — not enough consistent matches.")

        n_inliers = int(inliers.sum()) if inliers is not None else 0
        n_good    = len(good)

        # ── Step 4: Confidence ────────────────────────────────────────────
        inlier_ratio = n_inliers / max(n_good, 1)
        coverage     = min(n_inliers / 20.0, 1.0)   # saturates at 20 inliers
        confidence   = float(np.clip(inlier_ratio * coverage * 100.0, 0.0, 100.0))

        # ── Step 5: Transform mask polygons ──────────────────────────────
        aligned                  = ref_mask.transform(warp, (H, W))
        aligned.align_confidence = confidence
        aligned.n_match_inliers  = n_inliers   # stored for UI display

        return aligned, confidence

    # ── Template matching: replicate one polygon to all similar regions ───

    @staticmethod
    def find_similar_regions(
        image:          np.ndarray,
        template_poly:  list,
        threshold:      float = 0.50,
        max_results:    int   = 50,
    ) -> list:
        """
        Given ONE drawn polygon, find ALL visually similar regions in the image.

        matchTemplate result at (rx, ry) means: template top-left is at (rx, ry)
        in the image. So polygon offset = (rx - tx1, ry - ty1).
        Multi-scale: for each scale we store (score, img_x, img_y) using the
        correct image-space coordinates — no padding, no coordinate drift.
        """
        gray = MaskEngine._to_gray_8bit(image)
        H, W = gray.shape

        # Bounding box of the drawn polygon (template region)
        xs = [p[0] for p in template_poly]
        ys = [p[1] for p in template_poly]
        tx1 = max(0, min(xs));  ty1 = max(0, min(ys))
        tx2 = min(W - 1, max(xs)); ty2 = min(H - 1, max(ys))
        tw, th = tx2 - tx1, ty2 - ty1

        if tw < 8 or th < 8:
            return [template_poly]

        template = gray[ty1:ty2, tx1:tx2].copy()

        # Collect (score, result_x, result_y, scale) across multiple scales
        # result_x/y are in matchTemplate result space; convert to image space below.
        candidates: list[tuple] = []

        for scale in (0.85, 0.92, 1.0, 1.08, 1.15):
            sw = max(8, int(tw * scale))
            sh = max(8, int(th * scale))
            if sw >= W or sh >= H:
                continue
            t_scaled  = cv2.resize(template, (sw, sh), interpolation=cv2.INTER_LINEAR)
            result    = cv2.matchTemplate(gray, t_scaled, cv2.TM_CCOEFF_NORMED)
            # result[ry, rx] → template top-left at (rx, ry) in IMAGE space (no offset)
            locs = np.argwhere(result >= threshold)   # (row, col) = (ry, rx)
            for ry, rx in locs:
                score = float(result[ry, rx])
                # Convert match top-left back to center of the original template
                # so NMS suppression is center-based
                cx_img = rx + sw // 2   # center-x in image
                cy_img = ry + sh // 2   # center-y in image
                # Polygon offset: where the template top-left landed vs original
                dx = rx - tx1
                dy = ry - ty1
                candidates.append((score, cx_img, cy_img, dx, dy))

        if not candidates:
            return [template_poly]

        # Sort by score descending
        candidates.sort(key=lambda c: -c[0])

        # NMS: greedy, suppress within (tw, th) radius of each accepted center
        suppress_rx = tw * 0.6
        suppress_ry = th * 0.6
        accepted: list[tuple] = []
        for cand in candidates:
            score, cx, cy, dx, dy = cand
            # Check overlap with already accepted centers
            too_close = any(
                abs(cx - ac[1]) < suppress_rx and abs(cy - ac[2]) < suppress_ry
                for ac in accepted
            )
            if not too_close:
                accepted.append(cand)
            if len(accepted) >= max_results:
                break

        # Build output polygons
        result_polys = []
        for score, cx, cy, dx, dy in accepted:
            new_poly = [
                [max(0, min(p[0] + dx, W - 1)),
                 max(0, min(p[1] + dy, H - 1))]
                for p in template_poly
            ]
            result_polys.append(new_poly)

        return result_polys if result_polys else [template_poly]

    # ── Helpers ───────────────────────────────────────────────────────────

    @staticmethod
    def _to_gray_8bit(image: np.ndarray) -> np.ndarray:
        if image.dtype == np.uint16:
            image = (image >> 8).astype(np.uint8)
        img = image.astype(np.uint8)
        if img.ndim == 3:
            return cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        return img

    @staticmethod
    def _to_8bit(image: np.ndarray) -> np.ndarray:
        if image.dtype == np.uint16:
            return (image >> 8).astype(np.uint8)
        if image.dtype != np.uint8:
            return cv2.normalize(image, None, 0, 255,
                                 cv2.NORM_MINMAX).astype(np.uint8)
        return image
