"""
Inspection mask system — three-phase implementation.

Phase 1: Manual polygon mask — user draws the valid inspection region.
Phase 2: Auto-detect specular reflections → suggest exclusion mask.
Phase 3: Shape-based mask alignment — transfer mask from reference image
         to a new image using Phase Correlation + ECC refinement.

Research basis:
  Phase Correlation : Foroosh et al. 2002, IEEE Trans. Image Processing
  ECC alignment     : Evangelidis & Psarakis 2008, IEEE Trans. PAMI
  Canny edge map    : Canny 1986, used as stable feature for alignment
  Chamfer distance  : Borgefors 1988 (fallback confidence validation)

Confidence:
  HIGH   (>=80%)  — ECC converged + phase correlation consistent
  MEDIUM (50-79%) — apply with user confirmation
  LOW    (<50%)   — alignment uncertain — warn, require manual verification

Convention: polygon = VALID INSPECTION REGION (white = inspect, black = exclude).
"""

import json
import numpy as np
import cv2
from dataclasses import dataclass
from typing import Optional


# ── Mask data ──────────────────────────────────────────────────────────────

@dataclass
class MaskData:
    """
    One or more polygons defining the VALID inspection region.
    Pixels inside polygons → analyzed by focus + quality engines.
    Pixels outside → excluded from all metrics.
    """
    polygons:         list         # list of polygons; each = list of [x, y] int pairs
    image_shape:      tuple        # (H, W) of the source image
    source_image:     str  = ""    # filename this was drawn/detected on
    auto_detected:    bool = False  # True if generated by detect_reflections()
    align_confidence: float = 100.0 # 0–100; set by align_mask()

    # ── Rasterization ───────────────────────────────────────────────────

    def to_array(self, target_shape: tuple = None) -> np.ndarray:
        """
        Rasterize all polygons into a binary mask.
        Returns uint8 array same size as target_shape (or image_shape):
          1 = inspect this pixel
          0 = exclude this pixel
        If no polygons: all-ones (full image analyzed).
        """
        H, W = target_shape if target_shape else self.image_shape
        if not self.polygons:
            return np.ones((H, W), dtype=np.uint8)
        mask = np.zeros((H, W), dtype=np.uint8)
        for poly in self.polygons:
            pts = np.array(poly, dtype=np.int32).reshape(-1, 1, 2)
            cv2.fillPoly(mask, [pts], 1)
        return mask

    def coverage_pct(self, target_shape: tuple = None) -> float:
        """Percentage of image area inside the mask (inspection region)."""
        arr = self.to_array(target_shape)
        return float(arr.sum()) / arr.size * 100.0

    # ── Geometric transform ──────────────────────────────────────────────

    def transform(self, warp_matrix: np.ndarray,
                  target_shape: tuple) -> "MaskData":
        """
        Apply a 2×3 affine (Euclidean) warp to all polygon vertices.
        Returns a new MaskData in target_shape coordinates.
        """
        H, W = target_shape
        new_polys = []
        for poly in self.polygons:
            if not poly:
                continue
            pts = np.array(poly, dtype=np.float32).reshape(-1, 1, 2)
            t   = cv2.transform(pts, warp_matrix).reshape(-1, 2)
            t[:, 0] = np.clip(t[:, 0], 0, W - 1)
            t[:, 1] = np.clip(t[:, 1], 0, H - 1)
            new_polys.append(t.astype(int).tolist())
        return MaskData(
            polygons         = new_polys,
            image_shape      = target_shape,
            source_image     = self.source_image,
            auto_detected    = self.auto_detected,
            align_confidence = self.align_confidence,
        )

    # ── Persistence ──────────────────────────────────────────────────────

    def save(self, path: str):
        with open(path, "w", encoding="utf-8") as f:
            json.dump({
                "polygons":         self.polygons,
                "image_shape":      list(self.image_shape),
                "source_image":     self.source_image,
                "auto_detected":    self.auto_detected,
                "align_confidence": self.align_confidence,
            }, f, indent=2)

    @classmethod
    def load(cls, path: str) -> "MaskData":
        with open(path, encoding="utf-8") as f:
            d = json.load(f)
        return cls(
            polygons         = d["polygons"],
            image_shape      = tuple(d["image_shape"]),
            source_image     = d.get("source_image",     ""),
            auto_detected    = d.get("auto_detected",    False),
            align_confidence = d.get("align_confidence", 100.0),
        )


# ── Mask engine ────────────────────────────────────────────────────────────

class MaskEngine:

    # ── Phase 2: Auto-detect specular reflections ─────────────────────────

    @staticmethod
    def detect_reflections(
        image:          np.ndarray,
        bright_thresh:  int   = 228,
        sat_thresh:     int   = 55,
        min_area_pct:   float = 0.3,
    ) -> Optional[MaskData]:
        """
        Detect specular reflection regions and return a MaskData that defines
        the VALID inspection region (everything except the reflections).

        Specular reflections in industrial images are:
          - Very bright  (HSV V channel > bright_thresh)
          - Nearly white (HSV S channel < sat_thresh — colorless)

        Both conditions together isolate specular highlights far better than
        brightness alone (which would also flag light-colored parts).

        Returns None if no significant reflections are found.
        """
        img8 = MaskEngine._to_8bit(image)
        if img8.ndim == 2:
            bgr = cv2.cvtColor(img8, cv2.COLOR_GRAY2BGR)
        else:
            bgr = cv2.cvtColor(img8, cv2.COLOR_RGB2BGR)

        H, W = bgr.shape[:2]
        hsv  = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
        V    = hsv[:, :, 2]
        S    = hsv[:, :, 1]

        # Specular mask: bright AND desaturated
        spec = ((V > bright_thresh) & (S < sat_thresh)).astype(np.uint8) * 255

        # Morphological operations:
        #   Close (21×21)  — fill holes inside reflection blobs
        #   Open  (5×5)    — remove isolated noise pixels
        k21 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (21, 21))
        k5  = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,   5))
        spec = cv2.morphologyEx(spec, cv2.MORPH_CLOSE, k21)
        spec = cv2.morphologyEx(spec, cv2.MORPH_OPEN,  k5)

        contours, _ = cv2.findContours(spec, cv2.RETR_EXTERNAL,
                                        cv2.CHAIN_APPROX_SIMPLE)
        min_area    = H * W * (min_area_pct / 100.0)
        large       = [c for c in contours if cv2.contourArea(c) >= min_area]

        if not large:
            return None   # no significant specular reflections detected

        # Build reflection mask, invert to get valid inspection region
        ref_mask = np.zeros((H, W), dtype=np.uint8)
        cv2.drawContours(ref_mask, large, -1, 255, thickness=cv2.FILLED)

        valid = cv2.bitwise_not(ref_mask)

        # Erode slightly to keep analysis away from reflection boundaries
        k15 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (15, 15))
        valid = cv2.erode(valid, k15)

        valid_ctrs, _ = cv2.findContours(valid, cv2.RETR_EXTERNAL,
                                          cv2.CHAIN_APPROX_SIMPLE)
        if not valid_ctrs:
            return None

        # Keep only the largest contiguous valid region
        main    = max(valid_ctrs, key=cv2.contourArea)
        peri    = cv2.arcLength(main, True)
        epsilon = 0.012 * peri          # Douglas-Peucker simplification
        approx  = cv2.approxPolyDP(main, epsilon, True)
        poly    = approx.reshape(-1, 2).tolist()

        return MaskData(
            polygons      = [poly],
            image_shape   = (H, W),
            auto_detected = True,
        )

    # ── Phase 3: Mask alignment ───────────────────────────────────────────

    @staticmethod
    def align_mask(
        ref_image:  np.ndarray,
        curr_image: np.ndarray,
        ref_mask:   MaskData,
    ) -> tuple:
        """
        Transfer ref_mask from ref_image pixel space to curr_image pixel space.

        Pipeline:
          1. Canny edge maps of both images
             (edges are stable across lighting/exposure changes)
          2. Phase correlation on blurred edge maps
             → robust coarse translation estimate (Foroosh 2002)
          3. ECC maximization initialized with phase result
             → refined Euclidean transform: Δx, Δy, θ (Evangelidis 2008)
          4. Confidence from phase response + ECC correlation value

        Returns: (aligned_MaskData, confidence_0_to_100)
        """
        ref_gray  = MaskEngine._to_gray_8bit(ref_image)
        curr_gray = MaskEngine._to_gray_8bit(curr_image)
        H, W      = curr_gray.shape

        # ── Step 1: Canny edge maps ────────────────────────────────────────
        ref_edges  = MaskEngine._canny_auto(ref_gray)
        curr_edges = MaskEngine._canny_auto(curr_gray)

        # Gaussian blur smooths edges → more robust phase correlation
        ref_blur  = cv2.GaussianBlur(ref_edges.astype(np.float32),  (5, 5), 1.0)
        curr_blur = cv2.GaussianBlur(curr_edges.astype(np.float32), (5, 5), 1.0)

        # ── Step 2: Phase correlation → coarse translation ─────────────────
        (tx, ty), pc_response = cv2.phaseCorrelate(ref_blur, curr_blur)

        # Reject implausibly large shifts (part cannot move >20% of frame)
        max_shift = min(H, W) * 0.20
        if abs(tx) > max_shift or abs(ty) > max_shift:
            tx, ty      = 0.0, 0.0
            pc_response = 0.0

        # ── Step 3: ECC refinement ─────────────────────────────────────────
        # Initialize warp from phase correlation result
        warp = np.float32([[1, 0, tx],
                            [0, 1, ty]])

        ecc_score = 0.0
        try:
            criteria = (
                cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,
                80,     # max iterations — more = more accurate, still fast
                1e-5,   # convergence epsilon — tight for production use
            )
            ecc_score, warp = cv2.findTransformECC(
                ref_blur, curr_blur,
                warp,
                cv2.MOTION_EUCLIDEAN,
                criteria,
                inputMask = None,
                gaussFiltSize = 5,
            )
        except cv2.error:
            # ECC did not converge — use phase result only, lower confidence
            ecc_score = float(pc_response) * 0.4

        # ── Step 4: Confidence score (0–100) ──────────────────────────────
        # pc_response: 0–1, good match ≈ 0.3–0.7
        # ecc_score:   0–1, good match ≈ 0.7–1.0
        phase_conf = min(float(pc_response) * 2.5, 1.0)
        ecc_conf   = max(0.0, (float(ecc_score) - 0.25) / 0.75)
        confidence = (0.35 * phase_conf + 0.65 * ecc_conf) * 100.0
        confidence = float(np.clip(confidence, 0.0, 100.0))

        # ── Step 5: Transform mask polygons ───────────────────────────────
        aligned                  = ref_mask.transform(warp, (H, W))
        aligned.align_confidence = confidence

        return aligned, confidence

    # ── Helpers ───────────────────────────────────────────────────────────

    @staticmethod
    def _canny_auto(gray: np.ndarray) -> np.ndarray:
        """Canny with thresholds derived from image statistics (not magic numbers)."""
        med   = float(np.median(gray[gray > 5]))  # ignore pure black background
        lower = int(max(10,  0.50 * med))
        upper = int(min(255, 1.50 * med))
        if upper - lower < 25:
            lower, upper = 30, 150
        return cv2.Canny(gray, lower, upper)

    @staticmethod
    def _to_gray_8bit(image: np.ndarray) -> np.ndarray:
        if image.dtype == np.uint16:
            image = (image >> 8).astype(np.uint8)
        img = image.astype(np.uint8)
        if img.ndim == 3:
            return cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        return img

    @staticmethod
    def _to_8bit(image: np.ndarray) -> np.ndarray:
        if image.dtype == np.uint16:
            return (image >> 8).astype(np.uint8)
        if image.dtype != np.uint8:
            return cv2.normalize(image, None, 0, 255,
                                 cv2.NORM_MINMAX).astype(np.uint8)
        return image
